 owner:
 name: Veronique Storme
 avatar: 
 bio: "This is an academic website."
 email: veronique.storme@psb.ugent.be
 # Do not include the @ symbol in your Twitter username
 twitter: CVS_UGent
 linkedin: veronique-storme-0815736
 github: vstorme
 orcid: 0000-0003-4762-6580
 google:
    scholar: Veronique Storme


theme: jekyll-theme-slate
plugins:
 - jekyll-relative-links
relative_links:
 enabled: true
 collections: true
include:
 - README.md
 - data_entry.md
 - FileNaming.md
 - NaturePapers.md
 - StatTest.md
 - workshops.md
 - seminars.md
 - links.md
    
