theme: jekyll-theme-slate
plugins:
 - jekyll-relative-links
relative_links:
 enabled: true
 collections: true
include:
 - README.md
 - data_entry.md
 - FileNaming.md
 - NaturePapers.md
 - StatTest.md
 - workshops.md
 - seminars.md
 - links.md
 
 [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/veronique-storme-0815736/"

 [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/CVS_UGent"
