 
title: PSB Biostatistics Page
email: veronique.storme@psb.ugent.be
theme: jekyll-theme-cayman
twitter_username: CVS_UGent
github_username:  vstorme
linkedin_username: veronique-storme-0815736
url: "https://vstorme.github.io/"
plugins:
 - jekyll-relative-links
relative_links:
 enabled: true
 collections: true
include:
 - index.md
 - data_entry.md
 - FileNaming.md
 - NaturePapers.md
 - StatTest.md
 - workshops.md
 - seminars.md
 - links.md
 
    
