theme: jekyll-theme-slate
plugins:
 - jekyll-relative-links
relative_links:
 enabled: true
 collections: true
include:
 - README.md
 - data_entry.md
 - FileNaming.md
 - NaturePapers.md
 - StatTest.md
 - workshops.md
 - seminars.md
 - links.md
